# Generated by Django 3.2.1 on 2024-02-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothetype',
            options={'verbose_name_plural': 'Type of cloth'},
        ),
        migrations.RemoveField(
            model_name='clothetype',
            name='number',
        ),
        migrations.CreateModel(
            name='Pre_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='number')),
                ('name', models.ManyToManyField(blank=True, to='laundry_app.ClotheType')),
            ],
        ),
    ]
