# Generated by Django 3.2.1 on 2024-02-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0002_auto_20240205_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_order',
            name='number',
        ),
    ]
