# Generated by Django 3.2.1 on 2024-02-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0003_remove_pre_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
