# Generated by Django 4.0.3 on 2024-02-06 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0004_alter_action_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='action',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cloth',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
