# Generated by Django 4.0.3 on 2024-02-08 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0006_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_Id',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
