# Generated by Django 4.0.3 on 2024-02-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0009_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cloth_price',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
