# Generated by Django 4.0.3 on 2024-02-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0012_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cloth_price',
        ),
    ]
