# Generated by Django 4.0.3 on 2024-03-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0017_rename_date_order_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AlterField(
            model_name='order',
            name='action',
            field=models.ForeignKey(blank=True, default='Pending', null=True, on_delete=django.db.models.deletion.SET_NULL, to='laundry_app.action'),
        ),
    ]
