# Generated by Django 4.0.3 on 2024-03-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0018_remove_order_service_alter_order_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='action',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laundry_app.action'),
        ),
        migrations.DeleteModel(
            name='Pre_order',
        ),
    ]
